services:

  php:
    build:
      context: ./deploy/php/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./deploy/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      #- ./deploy/php/crontab:/etc/crontabs/root
    container_name: php_ioc_di_php
    networks:
      - php_ioc_di
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/var/www:rw
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - php_ioc_di
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "54321:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h 127.0.0.1 -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./deploy/pgdata:/var/lib/postgresql/data
    container_name: php_ioc_di_db
    networks:
      - php_ioc_di

volumes:
  pgdata:

networks:
  php_ioc_di: